- name: Creates directory
  file: path={{database_path}} state=directory mode="u+rw,g-wx,o-rwx"

- name: Start MongoDB
  docker:
    name: biblicando-redis
    image: redis:alpine
    command: redis-server --appendonly yes
    state: started
    ports:
    - "6379:6379"

- name: Start redis
  docker:
    name: biblicando-mongodb
    image: mvertes/alpine-mongo
    state: started
    ports:
    - "27017:27017"
    volumes:
    - "{{database_path}}:/data/db"

- name: Set the environment variables
  lineinfile: dest=/etc/environment line="DB_HOST={{db_host}}"
  lineinfile: dest=/etc/environment line="DB_USERNAME={{db_username}}"
  lineinfile: dest=/etc/environment line="DB_PASSWORD={{db_password}}"
  lineinfile: dest=/etc/environment line="REDIS_HOST={{redis_host}}"
  lineinfile: dest=/etc/environment line="REDIS_PORT={{redis_port}}"
  lineinfile: dest=/etc/environment line="CACHE_CONFIG_FILE={{cache_config_file}}"
  lineinfile: dest=/etc/environment line="BIBLES_ORG_TOKEN={{bibles_org_token}}"